name: Build Android GKI Driver (Lite)
on:
  workflow_dispatch:
    inputs:
      driver_name:
        description: "驱动名 如 gs_mem.ko"
        required: true
        default: "gs_mem.ko"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install aarch64 toolchain
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu make bison flex libssl-dev libelf-dev

      - name: Download GKI Kernel Headers (arm64)
        run: |
          git clone --depth=1 https://github.com/terabbow/kernel-5.10-gki.git kernel

      - name: Copy driver
        run: |
          mkdir -p driver
          cp code/*.c code/*.h driver/

      - name: Makefile
        run: |
          cat > driver/Makefile << EOF
          obj-m += gs_mem.o
          EXTRA_CFLAGS += -Wno-unused-function -Wno-unused-variable -Wno-declaration-after-statement
          EOF

      - name: Build .ko
        run: |
          make -C $(pwd)/kernel \
            M=$(pwd)/driver \
            ARCH=arm64 \
            CROSS_COMPILE=aarch64-linux-gnu- \
            modules

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.driver_name }}
          path: driver/*.ko
